### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:/cygwin64\home\anfi\nanolang\graph.png'

### ISSUE THREAD

**Issue by Alezyn** [atom/image-view#103]
[Enter steps to reproduce:]

1. Open image file (png) in atom
2. Restart PC
3. Open atom again with image opened
4. Delete image with Windows Explorer
5. Close all tabs with context menu

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.61.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\cygwin64\home\anfi\nanolang\graph.png'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat 'C:\cygwin64\home\anfi\nanolang\graph.png'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at /app.asar/node_modules/image-view/lib/image-editor-view.js:35:42)
    at ImageEditor.get (/app.asar/node_modules/image-view/lib/image-editor.js:168:27)
    at ImageEditor.get (/app.asar/node_modules/image-view/lib/image-editor.js:162:18)
    at ViewRegistry.module.exports.ViewRegistry.createView (/app.asar/src/view-registry.js:101:35)
    at ViewRegistry.module.exports.ViewRegistry.getView (/app.asar/src/view-registry.js:84:21)
    at /app.asar/src/pane-element.js:132:29)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.addItem (/app.asar/src/pane.js:515:14)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:449:14)
    at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)
```

### Commands

```
  2x -0:40.2.0 tabs:close-all-tabs (li.texteditor.tab.sortable.active.modified.right-clicked)
```

### Non-Core Packages

```
language-tex 0.4.0 
latex 0.43.0 
```

**Comment by Alezyn** [comment]
Bug is already reported. Issue can be deleted.
