### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '$ATOM_HOME/.learn-ide\home\jpfingst-3214...

### ISSUE THREAD

**Issue by jcpny1** [atom/image-view#115]
[Enter steps to reproduce:]

1. Imported .JPG file.
2. Clicked on .JPG file in treeview, causing tab to open.
3. git added .JPG file.
4. git rm'd .JPG file.
5. rm -f'd .JPG file.
6. could not close .JPG file tab.
7. somehow, clicking on the tab, not only raised this error, but also replicated the tab, to a maximum of five tabs for the same missing .JPG file. Thereafter, no new tab was created, just the error was raised.

**Atom**: 2.4.2 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.60.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\John\.atom\.learn-ide\home\jpfingst-32149\code\labs\javascript-reduce-lab-v-000\IMG_2730.JPG'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat 'C:\Users\John\.atom\.learn-ide\home\jpfingst-32149\code\labs\javascript-reduce-lab-v-000\IMG_2730.JPG'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at ImageEditorView.module.exports.ImageEditorView.initialize (/app.asar/node_modules/image-view/lib/image-editor-view.js:96:34)
    at /app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at /app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at /app.asar/node_modules/image-view/lib/image-editor-view.js:16:52)
    at ViewRegistry.module.exports.ViewRegistry.createView (/app.asar/src/view-registry.js:134:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/app.asar/src/view-registry.js:84:21)
    at ImageEditorStatusView.module.exports.ImageEditorStatusView.updateImageSize (/app.asar/node_modules/image-view/lib/image-editor-status-view.js:68:40)
    at /app.asar/node_modules/image-view/lib/image-editor-status-view.js:40:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)
    at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)
```

### Commands

```
  2x -4:10.7.0 tree-view:remove (span.name.icon.icon-file-pdf)
     -3:36.8.0 learn-ide:import (span.name.icon.icon-file-directory)
     -2:38.1.0 tree-view:remove (li.file.entry.list-item.selected)
     -0:20.5.0 learn-ide:reset-connection (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide](https://atom.io/packages/learn-ide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
