### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '$ATOM_HOME/.learn-ide/home/nelsonmatthew...

### ISSUE THREAD

**Issue by Mnelson1992** [atom/image-view#139]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 2.5.3
**Learn IDE Core**: 2.5.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.6
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.60.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/mattnelson/.atom/.learn-ide/home/nelsonmatthew2015-51800/code/labs/riyadh-blog-v-000/MOCKUP.jpg'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/Users/mattnelson/.atom/.learn-ide/home/nelsonmatthew2015-51800/code/labs/riyadh-blog-v-000/MOCKUP.jpg'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at ImageEditorView.module.exports.ImageEditorView.initialize (/app.asar/node_modules/image-view/lib/image-editor-view.js:96:34)
    at /app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at /app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at /app.asar/node_modules/image-view/lib/image-editor-view.js:16:52)
    at ViewRegistry.module.exports.ViewRegistry.createView (/app.asar/src/view-registry.js:134:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/app.asar/src/view-registry.js:84:21)
    at /app.asar/src/pane-element.js:194:25)
    at /app.asar/src/pane-element.js:51:55)
    at /app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:852:27)
    at /packages/learn-ide-notifications/lib/notification-element.coffee:263:36)
    at /packages/learn-ide-notifications/lib/notification-element.coffee:235:6)
    at /packages/learn-ide-notifications/lib/notification-element.coffee:61:31
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Notification.module.exports.Notification.dismiss (/app.asar/src/notification.js:79:27)
    at /packages/learn-ide-notifications/lib/notification-element.coffee:238:12)
    at /packages/learn-ide-notifications/lib/notification-element.coffee:127:49)
```

### Commands

```
     -6:54.7.0 core:move-left (input.hidden-input)
  2x -6:49.5.0 core:backspace (input.hidden-input)
     -6:43.9.0 learn-ide:save (input.hidden-input)
     -5:37.2.0 snippets:next-tab-stop (input.hidden-input)
     -5:37.2.0 snippets:expand (input.hidden-input)
     -5:37.2.0 editor:indent (input.hidden-input)
     -5:05.3.0 learn-ide:save (input.hidden-input)
  2x -4:47.2.0 core:backspace (input.hidden-input)
     -4:38.7.0 learn-ide:save (input.hidden-input)
     -2:40.5.0 snippets:next-tab-stop (input.hidden-input)
     -2:40.5.0 snippets:expand (input.hidden-input)
     -2:40.5.0 editor:indent (input.hidden-input)
     -2:20.7.0 core:copy (span.syntax--markup.syntax--raw.syntax--gfm)
     -2:16.5.0 core:paste (span.syntax--punctuation.syntax--definition.syntax--string.syntax--end.syntax--html)
  2x -2:15.5.0 core:move-right (input.hidden-input)
     -1:57.6.0 learn-ide:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide](https://atom.io/packages/learn-ide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
