### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'nuclide:/our.hakobyant.sb.facebook.com/d...

### ISSUE THREAD

**Issue by hakobyant** [atom/image-view#144]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.61.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'nuclide:/our.hakobyant.sb.facebook.com/data/users/hakobyant/fbsource/fbcode/experimental/hakobyant/cxlab/catalina/all_scenarios_diagrams/SLA cycle: 8.png'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat 'nuclide:/our.hakobyant.sb.facebook.com/data/users/hakobyant/fbsource/fbcode/experimental/hakobyant/cxlab/catalina/all_scenarios_diagrams/SLA cycle: 8.png'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Proxy.fs.statSync (ELECTRON_ASAR.js:275:16)
    at new ImageEditorView (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor-view.js:39:48)
    at ImageEditor.get (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor.js:180:33)
    at ImageEditorStatusView.updateImageSize (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor-status-view.js:83:39)
    at ImageEditorStatusView.attach (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor-status-view.js:54:18)
    at new ImageEditorStatusView (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor-status-view.js:43:16)
    at Object.attachImageEditorStatusView (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/main.js:50:39)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/main.js:23:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:478:28)
    at WorkspaceCenter.paneContainer.onDidActivatePane (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:11:59)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:260:24)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:875:20)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:269:25)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:51:25)
```

### Commands

```
  2x -3:01.7.0 core:backspace (input.hidden-input)
  3x -3:00.0 core:save (input.hidden-input)
  2x -2:05.4.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.65.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.3 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.242.66273750 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this might be caused by the [Nuclide](https://atom.io/packages/nuclide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
