### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '$ATOM_HOME/packages/atom-wallaby/project...

### ISSUE THREAD

**Issue by JBGoldberg** [atom/image-view#152]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.61.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/goldberg/.atom/packages/atom-wallaby/projects/ec127bd27c50e2eb/instrumented/screen.png'

```
At fs.js:912

Error: ENOENT: no such file or directory, stat '/Users/goldberg/.atom/packages/atom-wallaby/projects/ec127bd27c50e2eb/instrumented/screen.png'
    at fs.statSync (fs.js:912:18)
    at Proxy.fs.statSync (ELECTRON_ASAR.js:280:16)
    at new ImageEditorView (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor-view.js:39:48)
    at ImageEditor.get (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor.js:180:33)
    at ImageEditor.get (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor.js:174:24)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:92:41)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:75:27)
    at HTMLElement.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:200:25)
    at HTMLElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:53:55)
    at HTMLElement.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:117:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:913:33)
    at NotificationElement.module.exports.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:294:46)
    at NotificationElement.module.exports.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:252:25)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:54:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Notification.module.exports.Notification.dismiss (/Applications/Atom.app/Contents/Resources/app/src/notification.js:79:33)
    at NotificationElement.module.exports.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:256:31)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:145:32)
```

### Commands

```
     -1:15.7.0 command-palette:toggle (textarea.)
     -1:12.6.0 core:move-down (input.hidden-input)
     -1:08.1.0 core:confirm (input.hidden-input)
     -1:08.1.0 wallaby:start (textarea.)
     -1:05.6.0 command-palette:toggle (textarea.)
  3x -1:03.0 core:move-down (input.hidden-input)
     -1:01.1.0 core:confirm (input.hidden-input)
     -1:01.1.0 wallaby:toggle-panel (textarea.)
     -0:58 command-palette:toggle (textarea.)
  8x -0:55.6.0 core:move-down (input.hidden-input)
  2x -0:48.9.0 core:move-up (input.hidden-input)
     -0:46 core:move-down (input.hidden-input)
     -0:45.5.0 core:move-up (input.hidden-input)
     -0:44.1.0 core:confirm (input.hidden-input)
     -0:44 wallaby:show-last-screenshot (textarea.)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angular2-snippets 0.4.0 
atom-beautify 0.30.5 
atom-typescript 11.0.7 
atom-wallaby 1.0.20 
busy-signal 1.4.3 
deckard 0.2.11 
emmet 2.4.3 
intentions 1.1.5 
language-typescript-grammars-only 1.6.0 
linter 2.2.0 
linter-ui-default 1.6.8 
nord-atom-syntax 0.9.1 
platformio-ide-terminal 2.6.0 
typescript-modules-helper 0.8.0 
```

**Comment by JBGoldberg** [comment]
Created by mistake
