### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '$ATOM_HOME/.learn-ide\home\AdamT213\box-...

### ISSUE THREAD

**Issue by AdamT213** [atom/image-view#155]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 3.0.0
**Learn IDE Core**: 3.0.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.60.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\Users\Adam Tropp\.atom\.learn-ide\home\AdamT213\box-style-codealong-v-000\images\white-wood.jpg'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat 'C:\Users\Adam Tropp\.atom\.learn-ide\home\AdamT213\box-style-codealong-v-000\images\white-wood.jpg'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at ImageEditorView.module.exports.ImageEditorView.initialize (/app.asar/node_modules/image-view/lib/image-editor-view.js:96:34)
    at /app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at /app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at /app.asar/node_modules/image-view/lib/image-editor-view.js:16:52)
    at ViewRegistry.module.exports.ViewRegistry.createView (/app.asar/src/view-registry.js:134:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/app.asar/src/view-registry.js:84:21)
    at /app.asar/src/pane-element.js:194:25)
    at /app.asar/src/pane-element.js:51:55)
    at /app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:852:27)
    at /app.asar/node_modules/learn-ide-3-notifications/lib/notification-element.js:298:40)
    at /app.asar/node_modules/learn-ide-3-notifications/lib/notification-element.js:256:19)
    at /app.asar/node_modules/learn-ide-3-notifications/lib/notification-element.js:59:26
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Notification.module.exports.Notification.dismiss (/app.asar/src/notification.js:79:27)
    at /app.asar/node_modules/learn-ide-3-notifications/lib/notification-element.js:260:25)
    at /app.asar/node_modules/learn-ide-3-notifications/lib/notification-element.js:149:26)
```

### Commands

```
     -4:49.9.0 core:backspace (input.hidden-input)
     -4:10.1.0 snippets:next-tab-stop (input.hidden-input)
     -4:10.1.0 snippets:expand (input.hidden-input)
     -4:10.1.0 editor:indent (input.hidden-input)
     -4:09.3.0 core:backspace (input.hidden-input)
     -4:02.9.0 learn-ide:save (input.hidden-input)
     -3:19.9.0 core:move-up (input.hidden-input)
     -2:41.3.0 learn-ide:save (input.hidden-input)
     -2:07.0 editor:indent-selected-rows (input.hidden-input)
     -2:03.3.0 snippets:next-tab-stop (input.hidden-input)
     -2:03.3.0 snippets:expand (input.hidden-input)
     -2:03.3.0 editor:indent (input.hidden-input)
     -1:55.1.0 snippets:next-tab-stop (input.hidden-input)
     -1:55.1.0 snippets:expand (input.hidden-input)
     -1:55.1.0 editor:indent (input.hidden-input)
     -1:52.6.0 learn-ide:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by Ben3eeE** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide package](https://atom.io/packages/learn-ide), not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
