### ISSUE TITLE
Failed to activate the image-view package

### ISSUE THREAD

**Issue by bender01sg** [atom/image-view#184]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [image-view](https://github.com/atom/image-view) package 0.63.1

### Stack Trace

Failed to activate the image-view package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/image-view-master/lib/main.coffee:2:5)
    at /packages/image-view-master/lib/main.coffee:1:1)
    at /packages/image-view-master/lib/main.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.30.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:782:33)
    at Package.activateNow (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:220:40)
    at measure (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.30.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.30.0/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.30.0/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.30.0/resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
asciidoc-image-helper 1.0.1 
atom-image-resize 0.3.0 
atom-languageclient 0.9.5 
global-background 0.4.0 
Hydrogen 2.6.0 
ide-csharp 0.6.2 
ide-php 0.7.15 
image-copipe 0.3.1 
image2react 0.5.3 
imagemin 1.6.1 
insert-image-to-atom-project 0.4.0 
markdown-image-assistant 0.2.1 
markdown-image-paste 2.5.2 
teletype 0.13.3 
```

**Comment by rsese** [comment]
Thanks for the report - I wonder if there was an update/installation problem.  Can you reinstall Atom and let us know if you still get the error?
