### ISSUE TITLE
Errors thrown when image-view tab is open and image file is deleted.

### ISSUE THREAD

**Issue by dantarion** [atom/image-view#74]
1. Open an image in a Atom tab with image-view enabled.
2. Delete image file outside of Atom (i.e. shell, etc)
3. Click on image-view tab for deleted file
4.
```
Error: ENOENT: no such file or directory, stat '/Users/eric/Desktop/IMAGE.png'
    at Error (native)
    at fs.statSync (fs.js:897:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:263:16)
    at ImageEditorView.module.exports.ImageEditorView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/image-view/lib/image-editor-view.js:100:34)
    at ImageEditorView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:184:25)
    at ImageEditorView.ScrollView [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new ImageEditorView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/image-view/lib/image-editor-view.js:20:52)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.itemRemoved (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:180:37)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:574:20)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:643:16)
    at atom-tabs.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:325:26)
    at Object.addElementCommands.tabs:close-tab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:95:26)
    at atom-tabs.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:86:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1133:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:354:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)
```

When I tried to replicate this exactly, sometimes Atom closes the tab itself, but sometimes it remains open and image-view attempts to reload the image file without checking to see if it still exists. The error popup reappears when closed and it becomes impossible to close the tabs.

**Comment by ungb** [comment]
I can't repro this issue.  @dantarion are you still able to on 1.14.3?

**Comment by Ben3eeE** [comment]
@ungb I was able to reproduce this with the Electron 1.4 branch (Outside of safe mode). I can posts steps later since I'm at work now :slightly_frowning_face:. Remind me in slack if I forget to post them :grinning:

**Comment by ungb** [comment]
I can repro this with steps @Ben3eeE provided:

```
1. Close all open Atom windows
2. Open Atom in the image-view repo
3. Close all empty tabs if any
4. Open spec/fixtures/binary-file-2.png
5. Open package.json
6. (package.json has focus and is the file open)
7. Close Atom
8. Open Atom (tab for spec/fixtures/binary-file-2.png is still open)
9. Delete spec/fixtures/binary-file-2.png
10. Switch to that tab and get error
```

**Comment by 50Wliu** [comment]
@Ben3eeE @ungb what would you say is the expected behavior in this case?  Close the image view automatically when we detect that the file no longer exists?
